=== ocean90/wba2-ss2013/WBA2 Phase 1/Aufgabe 3/3d-recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="recipe">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="subtitle" type="xs:string" minOccurs="0"/>
				<xs:element ref="category"/>
				<xs:element ref="images"/>
				<xs:element ref="ingredients"/>
				<xs:element ref="direction"/>
				<xs:element ref="comments"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="id"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="category">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="id"/>
			<xs:attribute type="xs:integer" name="parentId"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="images">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="image">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="author" minOccurs="0"/>
				<xs:element type="xs:anyURI" name="source"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="width" use="required"/>
			<xs:attribute type="xs:integer" name="height" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ingredients">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ingredient" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute type="xs:byte" name="portions"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ingredient">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="name" use="optional"/>
					<xs:attribute type="xs:float" name="amount" use="optional"/>
					<xs:attribute type="xs:string" name="unit" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="direction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="times"/>
				<xs:element type="xs:string" name="severity"/>
				<xs:element type="xs:short" name="calories"/>
				<xs:element ref="steps"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="times">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:byte" name="pre"/>
				<xs:element type="xs:byte" name="cook"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="step" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="comments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="comment"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="comment">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="commentAuthor">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name"/>
							<xs:element ref="avatar"/>
							<xs:element type="xs:integer" name="level"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element type="xs:dateTime" name="date"/>
				<xs:element type="xs:boolean" name="isHelpful"/>
				<xs:element type="xs:string" name="content"/>
				<xs:element name="replies">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="comment"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="commentAuthor">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name"/>
				<xs:element ref="avatar"/>
				<xs:element type="xs:int" name="level"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="avatar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ocean90/wba2-ss2013/WBA2 Phase 1/Aufgabe 3/3d-recipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipe
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="3d-recipe.xsd"
	id="24641006006067">
	<title>Lenchen’s Schokoladenkuchen</title>
	<category id="122" parentId="19">
		<name>Backen</name>
	</category>
	<images>
		<image width="420" height="280">
			<author>brutzelstube</author>
			<source>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/42942-420x280-fix-lenchen-s-schokoladenkuchen.jpg</source>
		</image>
		<image width="420" height="280">
			<author>Mutschkabras</author>
			<source>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/33241-420x280-fix-lenchen-s-schokoladenkuchen.jpg</source>
		</image>
	</images>
	<ingredients portions="16">
		<ingredient name="Butter" amount="200" unit="g"/>
		<ingredient name="Zucker" amount="200" unit="g"/>
		<ingredient name="Schokolade, Blockschokolade" amount="200" unit="g"/>
		<ingredient name="Mehl" amount="120" unit="g"/>
		<ingredient name="Backpulver" amount="0.5" unit="TL"/>
		<ingredient name="Vanillezucker" amount="1" unit="Pkt."/>
		<ingredient name="Ei(er)" amount="4"/>
	</ingredients>
	<direction>
		<times>
			<pre>60</pre>
			<cook>50</cook>
		</times>
		<severity>normal</severity>
		<calories>295</calories>
		<steps>
			<step>Butter und Schokolade im Wasserbad schmelzen.</step>
			<step>Eier trennen.</step>
			<step>Eiweiß steif schlagen.</step>
			<step>Eigelbe, Zucker und Vanillezucker verrühren.</step>
			<step>Geschmolzene Butter-Schokomasse hinzufügen und mischen.</step>
			<step>Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.</step>
			<step>In eine gut gefettete Form geben.</step>
			<step>Bei 180°Grad 40 – 50 Minuten backen.</step>
		</steps>
	</direction>
	<comments>
		<comment>
			<commentAuthor>
				<name>ClaudiaK43</name>
				<avatar>
					<image width="60" height="60">
						<source>http://static.chefkoch-cdn.de/ck.de/avatar/39a4daaaf3c439939466d8c582de8c18-60fix.jpg</source>
					</image>
				</avatar>
				<userLevel>1</userLevel>
			</commentAuthor>
			<date>2012-04-17T09:20:47</date>
			<isHelpful>true</isHelpful>
			<content>Kann mir jemand sagen welche Größe die Form bei diesem Rezpet haben muss?</content>
			<replies>
				<comment>
					<author>
						<name>esmiralda83</name>
						<avatar>
							<image width="60" height="60">
								<source>http://static.chefkoch-cdn.de/ck.de/avatar/39a4daaaf3c439939466d8c582de8c18-60fix.jpg</source>
							</image>
						</avatar>
						<userLevel>1</userLevel>
					</author>
					<date>2012-05-09T11:22:47</date>
					<isHelpful>false</isHelpful>
					<content>Ich nehme immer ne 26er Form! Klappt super!</content>
					<replies></replies>
				</comment>
			</replies>
		</comment>
	</comments>
</recipe>
