=== ocean90/wba2-ss2013/WBA2 Phase 1/misc/Aufgabe 3/3d-recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="recipes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="recipe" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="recipe">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="subtitle" type="xs:string" minOccurs="0"/>
				<xs:element ref="category"/>
				<xs:element ref="images" minOccurs="0"/>
				<xs:element ref="ingredients"/>
				<xs:element ref="direction"/>
				<xs:element ref="comments" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="id"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="category">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="id"/>
			<xs:attribute type="xs:integer" name="parentId" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="images">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="image">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="author" minOccurs="0"/>
				<xs:element type="xs:anyURI" name="source"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="width" use="required"/>
			<xs:attribute type="xs:integer" name="height" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ingredients">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ingredient" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="portions"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ingredient">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="name" use="required"/>
					<xs:attribute ref="amount" use="optional"/>
					<xs:attribute ref="unit" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="amount">
		<xs:simpleType>
			<xs:union>
				<xs:simpleType>
					<xs:restriction base="xs:float"/>
				</xs:simpleType>
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:union>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="unit" default="">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=""/>
				<xs:enumeration value="Becher"/>
				<xs:enumeration value="Beutel"/>
				<xs:enumeration value="Blatt"/>
				<xs:enumeration value="Blätter"/>
				<xs:enumeration value="Bund"/>
				<xs:enumeration value="Bündel"/>
				<xs:enumeration value="cl"/>
				<xs:enumeration value="cm"/>
				<xs:enumeration value="dicke"/>
				<xs:enumeration value="dl"/>
				<xs:enumeration value="Dose"/>
				<xs:enumeration value="Dose/n"/>
				<xs:enumeration value="dünne"/>
				<xs:enumeration value="Eimer"/>
				<xs:enumeration value="einige"/>
				<xs:enumeration value="einige Stiele"/>
				<xs:enumeration value="EL"/>
				<xs:enumeration value="EL, gest."/>
				<xs:enumeration value="etwas"/>
				<xs:enumeration value="evtl."/>
				<xs:enumeration value="extra"/>
				<xs:enumeration value="Flasche"/>
				<xs:enumeration value="Flaschen"/>
				<xs:enumeration value="g"/>
				<xs:enumeration value="Glas"/>
				<xs:enumeration value="Gläser"/>
				<xs:enumeration value="gr. Dose/n"/>
				<xs:enumeration value="gr. Fl."/>
				<xs:enumeration value="große"/>
				<xs:enumeration value="großen"/>
				<xs:enumeration value="großer"/>
				<xs:enumeration value="großes"/>
				<xs:enumeration value="halbe"/>
				<xs:enumeration value="Handvoll"/>
				<xs:enumeration value="kg"/>
				<xs:enumeration value="kl. Bund"/>
				<xs:enumeration value="kl. Dose/n"/>
				<xs:enumeration value="kl. Glas"/>
				<xs:enumeration value="kl. Kopf"/>
				<xs:enumeration value="kl.Flasche/n"/>
				<xs:enumeration value="kleine"/>
				<xs:enumeration value="kleinen"/>
				<xs:enumeration value="kleiner"/>
				<xs:enumeration value="kleines"/>
				<xs:enumeration value="Knolle/n"/>
				<xs:enumeration value="Kopf"/>
				<xs:enumeration value="Kugel"/>
				<xs:enumeration value="Kugel/n"/>
				<xs:enumeration value="Kugeln"/>
				<xs:enumeration value="Kästchen"/>
				<xs:enumeration value="Köpfe"/>
				<xs:enumeration value="Körner"/>
				<xs:enumeration value="Liter"/>
				<xs:enumeration value="m.-große"/>
				<xs:enumeration value="m.-großer"/>
				<xs:enumeration value="m.-großes"/>
				<xs:enumeration value="mehr"/>
				<xs:enumeration value="mg"/>
				<xs:enumeration value="ml"/>
				<xs:enumeration value="Msp."/>
				<xs:enumeration value="n. B."/>
				<xs:enumeration value="Paar"/>
				<xs:enumeration value="Paket"/>
				<xs:enumeration value="Pck."/>
				<xs:enumeration value="Pkt."/>
				<xs:enumeration value="Platte/n"/>
				<xs:enumeration value="Port."/>
				<xs:enumeration value="Prise"/>
				<xs:enumeration value="Prisen"/>
				<xs:enumeration value="Ring/e"/>
				<xs:enumeration value="Rippe/n"/>
				<xs:enumeration value="Scheibe/n"/>
				<xs:enumeration value="Scheiben"/>
				<xs:enumeration value="Schuss"/>
				<xs:enumeration value="Schälchen"/>
				<xs:enumeration value="Spritzer"/>
				<xs:enumeration value="Stange/n"/>
				<xs:enumeration value="Stiel/e"/>
				<xs:enumeration value="Stiele"/>
				<xs:enumeration value="Stück"/>
				<xs:enumeration value="Stängel"/>
				<xs:enumeration value="Tafel"/>
				<xs:enumeration value="Tafeln"/>
				<xs:enumeration value="Tasse"/>
				<xs:enumeration value="Tasse/n"/>
				<xs:enumeration value="Teil/e"/>
				<xs:enumeration value="TL"/>
				<xs:enumeration value="TL, gehäuft"/>
				<xs:enumeration value="TL, gestr."/>
				<xs:enumeration value="Topf"/>
				<xs:enumeration value="Tropfen"/>
				<xs:enumeration value="Tube/n"/>
				<xs:enumeration value="Tüte/n"/>
				<xs:enumeration value="viel"/>
				<xs:enumeration value="wenig"/>
				<xs:enumeration value="Wurzel"/>
				<xs:enumeration value="Wurzel/n"/>
				<xs:enumeration value="Würfel"/>
				<xs:enumeration value="Zehe/n"/>
				<xs:enumeration value="Zweig/e"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:element name="direction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="times" minOccurs="0"/>
				<xs:element ref="severity" minOccurs="0"/>
				<xs:element type="xs:integer" name="calories" minOccurs="0"/>
				<xs:element ref="steps"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="times">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:integer" name="pre" minOccurs="0"/>
				<xs:element type="xs:integer" name="cook" minOccurs="0"/>
				<xs:element type="xs:integer" name="rest" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="severity">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="simple"/>
				<xs:enumeration value="normal"/>
				<xs:enumeration value="pfiffig"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="step" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="comments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="comment" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="comment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="commentAuthor"/>
				<xs:element type="xs:dateTime" name="date"/>
				<xs:element type="xs:boolean" name="isHelpful" default="false"/>
				<xs:element type="xs:string" name="content"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="commentAuthor">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name"/>
				<xs:element ref="avatar" minOccurs="0"/>
				<xs:element type="xs:integer" name="userLevel"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="avatar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="image"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ocean90/wba2-ss2013/WBA2 Phase 1/Aufgabe 3/3d-recipes.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipes
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="3d-recipes.xsd">
	<recipe id="24641006006067">
		<title>Lenchen’s Schokoladenkuchen</title>
		<category id="122" parentId="19">
			<name>Backen</name>
		</category>
		<images>
			<image width="420" height="280">
				<author>brutzelstube</author>
				<source>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/42942-420x280-fix-lenchen-s-schokoladenkuchen.jpg</source>
			</image>
			<image width="420" height="280">
				<author>Mutschkabras</author>
				<source>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/33241-420x280-fix-lenchen-s-schokoladenkuchen.jpg</source>
			</image>
		</images>
		<ingredients portions="16">
			<ingredient name="Butter" amount="200" unit="g"/>
			<ingredient name="Zucker" amount="200" unit="g"/>
			<ingredient name="Schokolade, Blockschokolade" amount="200" unit="g"/>
			<ingredient name="Mehl" amount="120" unit="g"/>
			<ingredient name="Backpulver" amount="0.5" unit="TL"/>
			<ingredient name="Vanillezucker" amount="1" unit="Pkt."/>
			<ingredient name="Ei(er)" amount="4"/>
		</ingredients>
		<direction>
			<times>
				<pre>60</pre>
				<cook>50</cook>
			</times>
			<severity>normal</severity>
			<calories>295</calories>
			<steps>
				<step>Butter und Schokolade im Wasserbad schmelzen.</step>
				<step>Eier trennen.</step>
				<step>Eiweiß steif schlagen.</step>
				<step>Eigelbe, Zucker und Vanillezucker verrühren.</step>
				<step>Geschmolzene Butter-Schokomasse hinzufügen und mischen.</step>
				<step>Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.</step>
				<step>In eine gut gefettete Form geben.</step>
				<step>Bei 180°Grad 40 – 50 Minuten backen.</step>
			</steps>
		</direction>
		<comments>
			<comment>
				<commentAuthor>
					<name>ClaudiaK43</name>
					<avatar>
						<image width="60" height="60">
							<source>http://static.chefkoch-cdn.de/ck.de/avatar/39a4daaaf3c439939466d8c582de8c18-60fix.jpg</source>
						</image>
					</avatar>
					<userLevel>1</userLevel>
				</commentAuthor>
				<date>2012-04-17T09:20:47</date>
				<isHelpful>true</isHelpful>
				<content>Kann mir jemand sagen welche Größe die Form bei diesem Rezpet haben muss?</content>
				<replies>
					<comment>
						<author>
							<name>esmiralda83</name>
							<avatar>
								<image width="60" height="60">
									<source>http://static.chefkoch-cdn.de/ck.de/avatar/39a4daaaf3c439939466d8c582de8c18-60fix.jpg</source>
								</image>
							</avatar>
							<userLevel>1</userLevel>
						</author>
						<date>2012-05-09T11:22:47</date>
						<isHelpful>false</isHelpful>
						<content>Ich nehme immer ne 26er Form! Klappt super!</content>
						<replies></replies>
					</comment>
				</replies>
			</comment>
		</comments>
	</recipe>
</recipes>
